### ISSUE TITLE
$gitphp_conf['gitbin'] = '/usr/bin';

### ISSUE THREAD

**Issue by straweb** [xiphux/gitphp#24]
Could not run the git executable "/usr/bin". You may need to set the "gitbin" config value.

git is installed in /user/bin

in linux-godaddy shared hosting.

**Comment by xiphux** [comment]
The 'gitbin' config should be set to the path of the actual git executable, not the directory it's in.  So '/usr/bin/git', not just '/usr/bin'.

See the documentation on the option: http://www.gitphp.org/configuration-options/#gitbin

**Comment by straweb** [comment]
Even '/usr/bin/git' is not working

**Comment by xiphux** [comment]
Do you have any more info?  Does that executable actually exist?  Does your web server user have permission to execute it?  Is there any information in the php error log?
